version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile.ci
    volumes:
    - ./web:/app
    - node-modules:/app/node_modules
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.ci
    links:
    - db
    - redis
    volumes:
    - ./api:/app
    environment: 
      DATABASE_URL: postgres://postgres:password@db/myapp_test
      REDIS_URL: redis://redis:6379
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_test
  redis: 
    image: redis
volumes:
  db-data:
  bundle-data:
  node-modules: