version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile.dev
    ports:
    - "4200:4200"
    - "35729:35729"
    - "7357:7357"
    volumes:
    - ./web:/app
    - node-modules:/app/node_modules
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    ports:
    - "3000:3000"
    links:
    - db
    - redis
    - mail
    volumes:
    - ./api:/app
    - bundle-data:/bundle
    environment: 
      BUNDLE_PATH: /bundle/vendor
      DATABASE_URL: postgres://postgres:password@db/myapp_development
      REDIS_URL: redis://redis:6379
      MAIL_HOST: mail
      MAIL_PORT: 1025
  db:
    image: postgres:12
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
  redis: 
    image: redis
  mail: 
    build:
      context: .
      dockerfile: mail/Dockerfile.dev
    ports: 
    - "8025:8025"
volumes:
  db-data:
  bundle-data:
  node-modules: