name: Rails & Ember CI Tests

on: [push]

jobs:
  rails:
    name: Rails Test (RSpec)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker-compose -f docker-compose.ci.yml build api
    - name: Prepare
      run: docker-compose -f docker-compose.ci.yml run api rake db:test:prepare
    - name: RSpec
      run: docker-compose -f docker-compose.ci.yml run api rake 
  
  ember:
    name: Ember Test & Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker-compose -f docker-compose.ci.yml build web 
    - name: QUnit
      run: docker-compose -f docker-compose.ci.yml run web ember test
    - name: Lint
      run: docker-compose -f docker-compose.ci.yml run web yarn lint

  linter:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.0
        env:
          VALIDATE_RUBY: true