name: Test

on: [push]

jobs:
  rails:
    name: Rails
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Build
      run: docker-compose -f docker-compose.ci.yml build api
    - name: Prepare
      run: docker-compose -f docker-compose.ci.yml run api rake db:test:prepare
    - name: RSpec
      run: docker-compose -f docker-compose.ci.yml run api rake 
    - name: RuboCop
      run: docker-compose -f docker-compose.ci.yml run api bundle exec rubocop --require rubocop-rails
  
  
  ember:
    name: Ember
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Build
      run: docker-compose -f docker-compose.ci.yml build web 
    - name: QUnit
      run: docker-compose -f docker-compose.ci.yml run web ember test
    - name: Lint
      run: docker-compose -f docker-compose.ci.yml run web yarn lint
