name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Image
      run: |
        docker-compose -f docker-compose.ci.yml build

    - name: Run test suite
      run: |
        docker-compose run api rake db:test:prepare
        docker-compose run api rake 
