name: Rails & Ember CI Tests

on: [push]

jobs:
  rails:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Test Suite
      run: |
        set -e
        docker-compose -f docker-compose.ci.yml run api rake db:test:prepare
        docker-compose -f docker-compose.ci.yml run api rake 
  ember:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Image
      run: |
        docker-compose -f docker-compose.ci.yml build
    - name: Run Test Suite
      run: |
        set -e
        docker-compose -f docker-compose.ci.yml run web yarn test
