name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/caches/images.tar
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Load Images
      run: |
        set +o pipefail
        docker load -i ~/caches/images.tar | true

    - name: Prepare CI to run tests
      run: bin/ci/prepare

    - name: Save Images
      run: |
        mkdir -p ~/caches
        docker save $(docker images -q) -o ~/caches/images.tar

    - name: Run test suite
      run: docker-compose run api rake
